services:
    fastapi:
        image: pplmx/fastapi_sample
        restart: always
        ports:
            - "8000:8000"
        networks:
            - traefik-net

# Use external network
#networks:
#    traefik-net:
#        external: true

# Create a new network
networks:
    traefik-net:
        name: traefik-net
        ipam:
            config:
                -   subnet: 172.16.155.0/24
