version: Compose specification
services:
    fastapi:
        image: pplmx/fastapi_sample
        restart: always
        networks:
            - traefik-net

networks:
    traefik-net:
        external: true
