apiVersion: v1
kind: PersistentVolume
metadata:
    name: fastapi-sample-pv  # PersistentVolume的名称
spec:
    capacity:
        storage: 10Gi  # 定义存储容量, 这里是10GiB
    volumeMode: Filesystem  # 使用文件系统模式, 还可以是Block模式
    accessModes:
        - ReadWriteOnce  # 定义访问模式, 表示可以被单个节点读写
    persistentVolumeReclaimPolicy: Retain  # 定义回收策略, Retain表示在PVC被删除后保留PV
    storageClassName: standard  # 定义存储类, PVC会选择相同存储类的PV
    hostPath:  # 在节点上定义存储路径
        path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: fastapi-sample-pvc  # PersistentVolumeClaim的名称
spec:
    accessModes:
        - ReadWriteOnce  # 必须与PersistentVolume的访问模式匹配
    storageClassName: standard  # 必须与PersistentVolume的存储类匹配
    resources:
        requests:
            storage: 10Gi  # 必须小于或等于PersistentVolume的存储容量

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: fastapi-sample  # 部署的名称
    labels:
        app: fastapi-sample  # 标签, 用于选择器
spec:
    replicas: 3  # 副本数量,增加副本数量以提高可用性
    selector:
        matchLabels:
            app: fastapi-sample  # 选择器, 用于匹配Pod
    template:
        metadata:
            labels:
                app: fastapi-sample  # Pod的标签
        spec:
            containers:
                -   name: fastapi-sample  # 容器名称
                    image: pplmx/fastapi_sample  # 容器镜像
                    ports:
                        -   containerPort: 8080  # 容器端口
                    imagePullPolicy: IfNotPresent  # 如果镜像已经存在, 就不需要总是拉取
                    livenessProbe: # liveness探针, 用于检查容器是否还在运行
                        httpGet:
                            path: /livez # 服务提供的健康检查接口
                            port: 8080
                    readinessProbe: # readiness探针, 用于检查容器是否准备好处理请求
                        httpGet:
                            path: /ready # 服务提供的准备就绪接口
                            port: 8080
                    volumeMounts:  # 挂载卷到容器中的路径上
                        - name: data-volume
                          mountPath: /data
            volumes:   # 在Pod级别定义卷,可以被Pod中的所有容器使用
                - name: data-volume
                  persistentVolumeClaim:
                      claimName: fastapi-sample-pvc
    strategy: # 添加更新策略
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
            maxSurge: 1

---
apiVersion: v1
kind: Service
metadata:
    name: fastapi-sample-svc  # 服务名称
spec:
    selector:
        app: fastapi-sample  # 选择器, 用于匹配Pod
    ports:
        -   port: 18888  # 服务端口
            targetPort: 8080  # 目标端口, 即Pod的端口
    type: LoadBalancer  # 类型为LoadBalancer, 会自动创建云提供商的负载均衡器

---
apiVersion: autoscaling/v2  # 添加自动缩放以处理负载变化
kind: HorizontalPodAutoscaler
metadata:
    name: fastapi-sample-hpa  # 自动缩放器的名称
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: fastapi-sample  # 需要缩放的目标, 即上面定义的Deployment
    minReplicas: 3  # 最小副本数量
    maxReplicas: 10  # 最大副本数量, 根据需要, 可以增加最大副本数
    metrics:
        -   type: Resource
            resource:
                name: cpu
                target:
                    type: Utilization
                    averageUtilization: 85  # CPU利用率超过85%时, 自动扩容
        -   type: Resource
            resource:
                name: memory
                target:
                    type: Utilization
                    averageUtilization: 85 # 内存使用率超过85%时, 自动扩容
